/**
 * Central REST path map — aligned with backend (`/api/auth/*`, versioned `/api/:version/*`).
 * Version defaults to `v1` (Express: `app.use('/api/' + API_VERSION, routes)`).
 */
const API_ROOT = '/api';
const API_VERSION = import.meta.env.VITE_API_VERSION || 'v1';
const API_V = `${API_ROOT}/${API_VERSION}`;

export const endpoints = {
  auth: {
    login: `${API_ROOT}/auth/login`,
    accountStatus: `${API_ROOT}/auth/account-status`,
    logout: `${API_ROOT}/auth/logout`,
    register: `${API_ROOT}/auth/register`,
    registerUniversities: `${API_ROOT}/auth/register/universities`,
    registerSpecialties: `${API_ROOT}/auth/register/specialties`,
    verifyEmailOtp: `${API_ROOT}/auth/verify-email-otp`,
    resendEmailOtp: `${API_ROOT}/auth/resend-email-otp`,
    forgotPassword: `${API_ROOT}/auth/forgot-password`,
    verifyPasswordResetOtp: `${API_ROOT}/auth/verify-password-reset-otp`,
    resendPasswordResetOtp: `${API_ROOT}/auth/resend-password-reset-otp`,
    resetPassword: `${API_ROOT}/auth/reset-password`,
    registerUniversitySpecialties: (universityId) =>
      `${API_ROOT}/auth/register/universities/${universityId}/specialties`,
    refresh: `${API_ROOT}/auth/refresh`,
    me: `${API_ROOT}/auth/me`,
  },
  users: `${API_V}/users`,
  universities: `${API_V}/universities`,
  specialties: `${API_V}/specialties`,
  tracks: `${API_V}/tracks`,
  microCredentials: `${API_V}/micro-credentials`,
  learningOutcomes: `${API_V}/learning-outcomes`,
  cohorts: `${API_V}/cohorts`,
  student: `${API_V}/student`,
  enrollments: `${API_V}/enrollments`,
  sessions: `${API_V}/sessions`,
  attendanceRecords: `${API_V}/attendance-records`,
  assessments: `${API_V}/assessments`,
  rubrics: `${API_V}/rubrics`,
  submissions: `${API_V}/submissions`,
  grades: `${API_V}/grades`,
  rubricCriteria: `${API_V}/rubric-criteria`,
  students: `${API_V}/students`,
  evidence: `${API_V}/evidence`,
  qaReviews: `${API_V}/qa-reviews`,
  correctiveActions: `${API_V}/corrective-actions`,
  riskCases: `${API_V}/risk-cases`,
  integrityCases: `${API_V}/integrity-cases`,
  recognitionRequests: `${API_V}/recognition-requests`,
  recognitionDocuments: `${API_V}/recognition-documents`,
  certificates: `${API_V}/certificates`,
  notifications: `${API_V}/notifications`,
  adminNotificationRules: `${API_V}/admin/notification-rules`,
  adminNotificationTemplates: `${API_V}/admin/notification-templates`,
  adminNotificationsOps: `${API_V}/admin/notifications`,
  auditLogs: `${API_V}/audit-logs`,
  analytics: `${API_V}/analytics`,
  dashboard: `${API_V}/dashboard`,
  roles: `${API_V}/roles`,
  settings: `${API_V}/settings`,
  modules: `${API_V}/modules`,
  reports: `${API_V}/reports`,
  adminCourses: `${API_V}/admin/courses`,
  studentCourses: `${API_V}/student/courses`,
  adminFieldTraining: `${API_V}/admin/field-training`,
  academicFieldTraining: `${API_V}/academic/field-training`,
  analytics: `${API_V}/analytics`,
  instructorFieldTraining: `${API_V}/instructor/field-training`,
  studentFieldTraining: `${API_V}/student/field-training`,
  help: `${API_V}/help`,
  studentHelp: `${API_V}/student`,
  adminHelp: `${API_V}/admin/help`,
  adminUserGuides: `${API_V}/admin/user-guides`,
  onboarding: `${API_V}/onboarding`,
  adminPopups: `${API_V}/admin/popups`,
  popups: `${API_V}/popups`,
  adminAnnouncements: `${API_V}/admin/announcements`,
  announcements: `${API_V}/announcements`,
  files: {
    presignUpload: `${API_V}/files/presign-upload`,
    confirmUpload: `${API_V}/files/confirm-upload`,
    downloadUrl: (id) => `${API_V}/files/${id}/download-url`,
    delete: (id) => `${API_V}/files/${id}`,
    health: `${API_V}/files/health/storage`,
  },
  ai: {
    generate: `${API_V}/ai/generate`,
    status: `${API_V}/ai/status`,
    test: `${API_V}/ai/test`,
  },
  public: {
    landingStats: `${API_V}/public/landing-stats`,
  },
};
