export const fieldTrainingKeys = {
  all: ['fieldTraining'],
  adminList: (params = {}) => [...fieldTrainingKeys.all, 'admin', 'list', params],
  adminStats: (params = {}) => [...fieldTrainingKeys.all, 'admin', 'stats', params],
  adminDetail: (id) => [...fieldTrainingKeys.all, 'admin', 'detail', id],
  adminApplications: (id) => [...fieldTrainingKeys.all, 'admin', 'applications', id],
  studentList: (params = {}) => [...fieldTrainingKeys.all, 'student', 'list', params],
  studentDetail: (id) => [...fieldTrainingKeys.all, 'student', 'detail', id],
  studentProgress: (id) => [...fieldTrainingKeys.all, 'student', 'progress', id],
  studentSessions: (id) => [...fieldTrainingKeys.all, 'student', 'sessions', id],
  studentAssessments: (id) => [...fieldTrainingKeys.all, 'student', 'assessments', id],
  myApplications: () => [...fieldTrainingKeys.all, 'student', 'myApplications'],
  tasks: (opportunityId, scope = 'admin') => [...fieldTrainingKeys.all, scope, 'tasks', opportunityId],
  submissions: (opportunityId) => [...fieldTrainingKeys.all, 'admin', 'submissions', opportunityId],
  sessions: (opportunityId) => [...fieldTrainingKeys.all, 'sessions', opportunityId],
  instructors: () => [...fieldTrainingKeys.all, 'instructors'],
  assessments: (opportunityId) => [...fieldTrainingKeys.all, 'assessments', opportunityId],
  sessionAttendance: (sessionId) => [...fieldTrainingKeys.all, 'attendance', sessionId],
  sessionParticipants: (sessionId) => [...fieldTrainingKeys.all, 'participants', sessionId],
  applicationProgress: (applicationId) => [...fieldTrainingKeys.all, 'progress', applicationId],
};
